version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=passroot
      - MARIADB_DATABASE=wordpress
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
